### ISSUE TITLE
paginate with filter not working

### ISSUE THREAD

**Issue by badrusalsyihab** [infernobass7/vue-paging#1]
hy infernobass7, I have read from https://laracasts.com/discuss/channels/vue/vuejs-how-to-make-pagination-with-limiter-and-range and you say "My component has the root object handle the filtering of the items."  but if I'm implementation your code it's not working ..
please check this out https://jsfiddle.net/badvz/xakvbzur/6/

thanks

**Comment by likeadeckofcards** [comment]
Hello @badrusalsyihab,
Thank you for your comments. There was a couple of things that I noticed. The count was set to 1, which meant one per page. Also, limitBy and filterBy are order specific. So limiting the filtering means it will only filter the limited snippet. Also, you may wish to set name that you are binding to to null or an empty string in data.

Here is my edits: https://jsfiddle.net/xakvbzur/8/
